# Generated by Django 3.2.5 on 2021-09-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_paid',
            new_name='paid',
        ),
    ]
