# Generated by Django 3.2.5 on 2021-09-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210912_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
